### ISSUE TITLE
Open up for Linux?

### ISSUE THREAD

**Issue by Narsail** [cpageler93/JiraSwift#8]
Hi there,

is there a restriction why this library and the underlying api-client are restricted to Apple environments? I would like to use your JiraSwift on linux.

Best
David

**Comment by cpageler93** [comment]
Hi @Narsail,

I don't think that there is any kind of restriction. [cpageler93/api-client](https://github.com/cpageler93/api-client) is just a small wrapper for [swift-server/async-http-client](https://github.com/swift-server/async-http-client), which makes it much easier to implement all the methods. Both libraries should work on all supported swift platforms.

I'm using HTTP client libraries like this, based on [cpageler93/api-client](https://github.com/cpageler93/api-client), in some of my Vapor Backend Apps (which are running on Ubuntu in a Docker container) as well as in some of my iOS Apps.

There is a Dockerfile in this project, so you can try to compile the library on Linux
`docker build --tag jira_swift .` or don't you think that this is a valid proof?

**Comment by Narsail** [comment]
Based on the package.swift content I thought you do not support linux. But I'm not completely aware of the implications of specifying a platform in the package file. If it is still working, I should be fine. Thanks 👍

**Comment by cpageler93** [comment]
Oh you're right.. I didn't know that there is [`.linux`](https://developer.apple.com/documentation/swift_packages/platform/3112702-linux) which I can add as a platform. Strangely it still works with docker. However, I think I can add `.linux` to the list of supported platforms.

**Comment by cpageler93** [comment]
@Narsail I think it's not allowed to add `.linux` as a supported platform
https://forums.swift.org/t/supportedplatform-linux-not-allowed/28500

I got the following error:
```swift
../JiraSwift: error: manifest parse error(s):
../JiraSwift/Package.swift:12:9: error: type 'SupportedPlatform' has no member 'linux'
```

I think it's okay if we keep it that way. The important part is, that it does work with linux as well.
